### ISSUE TITLE
Simplify site structure

### ISSUE THREAD

**Issue by vallahaye** [vallahaye/go.vallahaye.net#8]
The current navigation relies on redirects because we're serving Go module pages in a subfolder (`/modules/`) when "go get" tries to find those pages at the root. This system is cumbersome and could be reworked to serve Go module pages directly in the right place.

Concretely, the goal is to transform the website's structure from this:

```
public/
├── index.html
├── modules
│   ├── batcher
│   │   └── index.html
│   ├── connect-gateway
│   │   └── index.html
│   └── protobson
│       └── index.html
├── _redirects
└── sitemap.xml
```

To this:

```
public/
├── batcher.html
├── connect-gateway.html
├── index.html
├── protobson.html
└── sitemap.xml
```

[Hugo's ugly URLs](https://gohugo.io/content-management/urls/#appearance) combined with [Cloudflare Pages' ability to match extension-less routes](https://developers.cloudflare.com/pages/configuration/serving-pages/#route-matching) makes it possible.

**Tasks:**

- [x] Remove the `_redirects` asset
- [x] Add a new `_default/single.html` page layout and remove `modules/single.html`
- [x] Add a new `default` archetype and remove the `modules` archetype
- [x] Move the contents of the `modules` subfolder above it
- [x] Refactor the `hugo-new-module` script to do as much processing as possible outside the archetype
- [x] Enable Hugo's ugly URLs
- [x] Update the README accordingly
